<h2 style="color:green" align="center">Predicting if a person would buy from based on his age and other data using Decision Tree</h2>

In [24]:
import pandas as pd
import numpy as np
from matplotlib import pyplot as plt
from sklearn.linear_model import LogisticRegression
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_squared_error,mean_absolute_error,r2_score
from sklearn.preprocessing import LabelEncoder
from sklearn.tree import DecisionTreeClassifier

In [2]:
df = pd.read_csv('shop data.csv')
df

age  income  gender m_status buys
0     <25    high    male   single   no
1     <25    high    male  married   no
2   25-35    high    male   single  yes
3     >35  medium    male   single  yes
4     >35     low  female   single  yes
5     >35     low  female   single   no
6   25-35     low  female  married  yes
7     <25  medium    male  married   no
8     <25     low  female   single  yes
9     >35  medium  female  married  yes
10    <25  medium  female   single  yes
11  25-35  medium    male  married  yes
12  25-35    high  female   single  yes
13    >35  medium    male  married   no
14    <25    high    male   single   no
15    <25    high  female  married  yes
16    >35  medium    male  married  yes
17    <25    high  female   single  yes
18  25-35  medium  female  married  yes
19  25-35    high    male   single  yes
20    >35  medium  female  married   no
21    <25     low    male   single  yes

In [13]:
X=df.drop('buys',axis=1)
X

age  income  gender m_status
0     <25    high    male   single
1     <25    high    male  married
2   25-35    high    male   single
3     >35  medium    male   single
4     >35     low  female   single
5     >35     low  female   single
6   25-35     low  female  married
7     <25  medium    male  married
8     <25     low  female   single
9     >35  medium  female  married
10    <25  medium  female   single
11  25-35  medium    male  married
12  25-35    high  female   single
13    >35  medium    male  married
14    <25    high    male   single
15    <25    high  female  married
16    >35  medium    male  married
17    <25    high  female   single
18  25-35  medium  female  married
19  25-35    high    male   single
20    >35  medium  female  married
21    <25     low    male   single

In [18]:
y= df[['buys']]
y
#y= df.buys
#y[3]

buys
0    no
1    no
2   yes
3   yes
4   yes
5    no
6   yes
7    no
8   yes
9   yes
10  yes
11  yes
12  yes
13   no
14   no
15  yes
16  yes
17  yes
18  yes
19  yes
20   no
21  yes

In [22]:
le_X = LabelEncoder()
X = X.apply(le_X.fit_transform)
X

age  income  gender  m_status
0     1       0       1         1
1     1       0       1         0
2     0       0       1         1
3     2       2       1         1
4     2       1       0         1
5     2       1       0         1
6     0       1       0         0
7     1       2       1         0
8     1       1       0         1
9     2       2       0         0
10    1       2       0         1
11    0       2       1         0
12    0       0       0         1
13    2       2       1         0
14    1       0       1         1
15    1       0       0         0
16    2       2       1         0
17    1       0       0         1
18    0       2       0         0
19    0       0       1         1
20    2       2       0         0
21    1       1       1         1

In [23]:
X_train,X_test,y_train,y_test = train_test_split(X,y, test_size=0.3,random_state=3)

In [25]:
dest= DecisionTreeClassifier()
dest.fit(X_train,y_train)

DecisionTreeClassifier()

In [26]:
dest.predict(X_test)

array(['yes', 'no', 'no', 'no', 'yes', 'no', 'yes'], dtype=object)

In [27]:
y_test

buys
20   no
13   no
16  yes
1    no
2   yes
14   no
12  yes

In [28]:
dest.score(X_test,y_test)

0.7142857142857143

<h3>Performance using cross_val_score</h3>

In [29]:
from sklearn.model_selection import cross_val_score

In [32]:
result = cross_val_score(DecisionTreeClassifier(),X,y,cv=6) # cv=6 means 6 times data split and obtain model score 
result

array([0.75      , 0.75      , 0.75      , 0.75      , 1.        ,
       0.33333333])

In [33]:
result.mean()

np.float64(0.7222222222222222)

In [34]:
L_result = cross_val_score(LogisticRegression(),X,y,cv=6)
L_result


c:\Users\USER\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\USER\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\USER\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1339: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)
c:\Users\USER\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\utils\validation.py:1339: DataConve

array([0.25      , 0.75      , 0.75      , 0.75      , 0.66666667,
       0.66666667])

In [35]:
L_result.mean()

np.float64(0.6388888888888888)

In [38]:
from sklearn.preprocessing import MinMaxScaler
MMS =MinMaxScaler()
X_scaled = MMS.fit_transform(X)
X_scaled

array([[0.5, 0. , 1. , 1. ],
       [0.5, 0. , 1. , 0. ],
       [0. , 0. , 1. , 1. ],
       [1. , 1. , 1. , 1. ],
       [1. , 0.5, 0. , 1. ],
       [1. , 0.5, 0. , 1. ],
       [0. , 0.5, 0. , 0. ],
       [0.5, 1. , 1. , 0. ],
       [0.5, 0.5, 0. , 1. ],
       [1. , 1. , 0. , 0. ],
       [0.5, 1. , 0. , 1. ],
       [0. , 1. , 1. , 0. ],
       [0. , 0. , 0. , 1. ],
       [1. , 1. , 1. , 0. ],
       [0.5, 0. , 1. , 1. ],
       [0.5, 0. , 0. , 0. ],
       [1. , 1. , 1. , 0. ],
       [0.5, 0. , 0. , 1. ],
       [0. , 1. , 0. , 0. ],
       [0. , 0. , 1. , 1. ],
       [1. , 1. , 0. , 0. ],
       [0.5, 0.5, 1. , 1. ]])

In [44]:
from sklearn.neighbors import KNeighborsClassifier
KNN_result = cross_val_score(KNeighborsClassifier(n_neighbors=3),X_scaled,y, cv=6)
KNN_result

c:\Users\USER\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
c:\Users\USER\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
c:\Users\USER\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\neighbors\_classification.py:238: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)
c:\Users\USER\AppData\Local\Programs\Python\Python312\Lib\site-packages\sklearn\neighbors\_classification.py:238: Data

array([0.75      , 0.75      , 0.75      , 0.75      , 0.66666667,
       0.        ])

In [45]:
KNN_result.mean()

np.float64(0.611111111111111)