In [1]:
import pandas as pd
import matplotlib.pyplot as plt
import numpy as np

In [2]:
df = pd.read_csv('shop data.csv')

In [3]:
df

age  income  gender m_status buys
0     <25    high    male   single   no
1     <25    high    male  married   no
2   25-35    high    male   single  yes
3     >35  medium    male   single  yes
4     >35     low  female   single  yes
5     >35     low  female   single   no
6   25-35     low  female  married  yes
7     <25  medium    male  married   no
8     <25     low  female   single  yes
9     >35  medium  female  married  yes
10    <25  medium  female   single  yes
11  25-35  medium    male  married  yes
12  25-35    high  female   single  yes
13    >35  medium    male  married   no
14    <25    high    male   single   no
15    <25    high  female  married  yes
16    >35  medium    male  married  yes
17    <25    high  female   single  yes
18  25-35  medium  female  married  yes
19  25-35    high    male   single  yes
20    >35  medium  female  married   no
21    <25     low    male   single  yes

In [4]:
x = df.drop('buys', axis=1) 

In [5]:
x

age  income  gender m_status
0     <25    high    male   single
1     <25    high    male  married
2   25-35    high    male   single
3     >35  medium    male   single
4     >35     low  female   single
5     >35     low  female   single
6   25-35     low  female  married
7     <25  medium    male  married
8     <25     low  female   single
9     >35  medium  female  married
10    <25  medium  female   single
11  25-35  medium    male  married
12  25-35    high  female   single
13    >35  medium    male  married
14    <25    high    male   single
15    <25    high  female  married
16    >35  medium    male  married
17    <25    high  female   single
18  25-35  medium  female  married
19  25-35    high    male   single
20    >35  medium  female  married
21    <25     low    male   single

In [6]:
#y = df.iloc[:,4]
y = df.buys

In [7]:
y

0      no
1      no
2     yes
3     yes
4     yes
5      no
6     yes
7      no
8     yes
9     yes
10    yes
11    yes
12    yes
13     no
14     no
15    yes
16    yes
17    yes
18    yes
19    yes
20     no
21    yes
Name: buys, dtype: object

In [8]:
from sklearn.preprocessing import LabelEncoder

In [9]:
le_x = LabelEncoder()
x = x.apply(le_x.fit_transform)

In [10]:
x

age  income  gender  m_status
0     1       0       1         1
1     1       0       1         0
2     0       0       1         1
3     2       2       1         1
4     2       1       0         1
5     2       1       0         1
6     0       1       0         0
7     1       2       1         0
8     1       1       0         1
9     2       2       0         0
10    1       2       0         1
11    0       2       1         0
12    0       0       0         1
13    2       2       1         0
14    1       0       1         1
15    1       0       0         0
16    2       2       1         0
17    1       0       0         1
18    0       2       0         0
19    0       0       1         1
20    2       2       0         0
21    1       1       1         1

In [11]:
from sklearn.model_selection import train_test_split
xtrain,xtest,ytrain,ytest = train_test_split(x,y,test_size=0.30, random_state=2)

In [12]:
xtrain

age  income  gender  m_status
10    1       2       0         1
9     2       2       0         0
4     2       1       0         1
5     2       1       0         1
16    2       2       1         0
1     1       0       1         0
2     0       0       1         1
7     1       2       1         0
18    0       2       0         0
17    1       0       0         1
11    0       2       1         0
21    1       1       1         1
13    2       2       1         0
15    1       0       0         0
8     1       1       0         1

In [13]:
xtest

age  income  gender  m_status
12    0       0       0         1
0     1       0       1         1
14    1       0       1         1
6     0       1       0         0
19    0       0       1         1
20    2       2       0         0
3     2       2       1         1

In [ ]:
ytest

In [ ]:
ytrain

In [15]:
from sklearn.tree import DecisionTreeClassifier
dect = DecisionTreeClassifier()
dect.fit(xtrain,ytrain)

DecisionTreeClassifier()

In [16]:
dect.predict(xtest)

array(['yes', 'yes', 'yes', 'yes', 'yes', 'yes', 'yes'], dtype=object)

In [17]:
ytest

12    yes
0      no
14     no
6     yes
19    yes
20     no
3     yes
Name: buys, dtype: object

In [18]:
dect.score(xtest, ytest)

0.5714285714285714

**Performance using cross_val_score**

In [19]:
from sklearn.model_selection import cross_val_score

In [20]:
result = cross_val_score(DecisionTreeClassifier(), x, y, cv=5)
result

array([0.6 , 0.6 , 0.75, 0.25, 0.5 ])

In [21]:
result.mean()

0.54

In [22]:
from sklearn.linear_model import LogisticRegression
result = cross_val_score(LogisticRegression(), x, y, cv=5)
result

array([0.4 , 0.6 , 0.75, 0.5 , 0.75])

In [23]:
result.mean()

0.6

In [24]:
from sklearn.preprocessing import MinMaxScaler

MMS = MinMaxScaler()

x_scaled = MMS.fit_transform(x)
x_scaled

array([[0.5, 0. , 1. , 1. ],
       [0.5, 0. , 1. , 0. ],
       [0. , 0. , 1. , 1. ],
       [1. , 1. , 1. , 1. ],
       [1. , 0.5, 0. , 1. ],
       [1. , 0.5, 0. , 1. ],
       [0. , 0.5, 0. , 0. ],
       [0.5, 1. , 1. , 0. ],
       [0.5, 0.5, 0. , 1. ],
       [1. , 1. , 0. , 0. ],
       [0.5, 1. , 0. , 1. ],
       [0. , 1. , 1. , 0. ],
       [0. , 0. , 0. , 1. ],
       [1. , 1. , 1. , 0. ],
       [0.5, 0. , 1. , 1. ],
       [0.5, 0. , 0. , 0. ],
       [1. , 1. , 1. , 0. ],
       [0.5, 0. , 0. , 1. ],
       [0. , 1. , 0. , 0. ],
       [0. , 0. , 1. , 1. ],
       [1. , 1. , 0. , 0. ],
       [0.5, 0.5, 1. , 1. ]])

In [ ]:
from sklearn.neighbors import KNeighborsClassifier
result = cross_val_score(KNeighborsClassifier(n_neighbors=3), x_scaled, y, cv=5)
result

In [ ]:
result.mean()

In [ ]:
y_predict = dect.predict(xtest)
y_predict

In [ ]:
from sklearn.metrics import classification_report, confusion_matrix

In [ ]:
print(classification_report(ytest,y_predict))

In [ ]:
#xinput = np.array([1,0,0,1])
xinput = np.array([1,0,1,1])

In [ ]:
y_predict = dect.predict([xinput])

In [ ]:
y_predict

In [ ]:
x.columns.tolist()

In [ ]:
from sklearn import tree
from matplotlib import pyplot as plt
fig=plt.figure(figsize=(30,20))
tree.plot_tree(dect, feature_names=x.columns.tolist(), filled=True, fontsize=20)

### Tree Explanation

<img src="tree.jpg" />